(function() {/*
 Copyright 2019 Glance Networks, Inc.
*/
var aa=["4","6","0","16"].slice(0,3).join(".");function h(a){for(a=a.toString();2>a.length;)a="0"+a;return a}Uint8Array.prototype.slice||(Uint8Array.prototype.slice=function(a,c){return new Uint8Array(this.subarray(a,c))});
ArrayBuffer.prototype.slice||(ArrayBuffer.prototype.slice=function(a,c){void 0===a&&(a=0);void 0===c&&(c=this.byteLength);a=Math.floor(a);c=Math.floor(c);0>a&&(a+=this.byteLength);0>c&&(c+=this.byteLength);a=Math.min(Math.max(0,a),this.byteLength);c=Math.min(Math.max(0,c),this.byteLength);if(0>=c-a)return new ArrayBuffer(0);var d=new ArrayBuffer(c-a),e=new Uint8Array(d),g=new Uint8Array(this,a,c-a);e.set(g);return d});
var l=navigator.userAgent.toLowerCase(),n=l.match(/(edge)[\s\/:]([\w\d\.]+)?/)||l.match(/(opera|ie|firefox|chrome|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||l.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"rv"===n[1]&&(n[1]="ie");/*
 Copyright 2017 Glance Networks, Inc.
*/
function ba(a){for(var c=new Date,c=c.getUTCFullYear()+"/"+(c.getUTCMonth()+1)+"/"+c.getUTCDate()+" "+h(c.getUTCHours())+":"+h(c.getUTCMinutes())+":"+h(c.getUTCSeconds())+" ",d=0;d<a.length;d++)c+=("object"===typeof a[d]?JSON.stringify(a[d]):a[d])+" ";return c}function p(a){window.console&&window.console.log&&window.console.log(ba(arguments))};/*
 Copyright (c) 2018 Glance Networks, Inc.
*/
var q=q||{};window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION="4.6.0.16";window.GLANCE.PATCH="";var r=navigator.userAgent.toLowerCase(),ca=navigator.platform.toLowerCase(),t=r.match(/(edge)[\s\/:]([\w\d\.]+)?/)||r.match(/(opera|ie|firefox|chrome|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||r.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"rv"===t[1]&&(t[1]="ie");
var u={extend:Function.prototype.extend,name:"version"==t[1]?t[3]:t[1],version:"ie"==t[1]&&document.documentMode||parseFloat("opera"==t[1]&&t[4]?t[4]:t[2]),u:{name:r.match(/ip(?:ad|od|hone)/)?"ios":(r.match(/(?:webos|android)/)||ca.match(/mac|win|linux/)||["other"])[0]},S:{W:!!document.evaluate,U:!!window.runtime,query:!!document.querySelector,json:!!window.JSON},T:{}};
document.documentMode&&window.XDomainRequest?(u.name="ie",u.version=document.documentMode):window.navigator&&navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&(u.name="ie",u.version="7");u[u.name]=!0;u[u.name+parseInt(u.version,10)]=!0;u.u[u.u.name]=!0;
if("undefined"!==typeof window.Prototype&&1.7>parseFloat(window.Prototype.Version.substr(0,3))&&"undefined"!==typeof Array.prototype.toJSON)var w=function(a){var c=Array.prototype.toJSON;delete Array.prototype.toJSON;a=JSON.stringify(a);Array.prototype.toJSON=c;return a};void 0===w&&(w=function(a){return JSON.stringify(a)});
function x(a){a.onmessage=function(c){c=JSON.parse(c.data);a.C&&a.C(c)};a.s=function(c){c=w(c);a.send(c)};a.H=function(a){return a&&a.code||0};a.I=function(a){return a&&a.reason||""}}
function da(a){var c={},d;q.P?d=new y(a):(u.ie9&&"http:"===window.location.protocol&&(c.protocols_whitelist=["iframe-eventsource","iframe-htmlfile"]),d=new SockJS(a,"",c));d.l=0;d.F=function(){d.w();d.transport&&!d.transport.match(/^iframe-/)&&(d.A=window.setInterval(function(){d.l++;d.M&&d.M({l:d.l})},15E3))};d.w=function(){d.A&&window.clearInterval(d.A)};x(d);d.onclose=function(a){d.w();d.K&&d.K(a)};d.onheartbeat=function(){d.l=0;d.F();d.L&&d.L()};return d}
function z(a,c){window.setTimeout(function(){z(a,c)},100)}function y(a){this.readyState=SockJS.CONNECTING;this.a=Math.round(1E6*Math.random());A=A||{};A[this.a]=this;z({from:"GSockJSProxy",sockid:this.a,cmd:"open",url:a})}var A;y.prototype.send=function(a){z({from:"GSockJSProxy",sockid:this.a,cmd:"send",data:a})};y.prototype.close=function(){this.readyState=SockJS.CLOSING;z({from:"GSockJSProxy",sockid:this.a,cmd:"close"})};
function B(a,c,d){void 0!==a&&(d=d||Object.keys(a),d.forEach(function(d){void 0!==a[d]&&(c[d]=a[d])}))}function ea(a){var c=a.func.split(".");if("GLANCE"!==c[0])C("ERR_BADINVOKE:"+c[0]);else{for(var d=window.GLANCE,e=1;e<c.length;e++)if(d=d[c[e]],!d){C("ERR_UNDEFINVOKE:"+c[e]);return}a.args=a.args||{};a.args.remote=!0;d(a.args)}}function D(a){q.P?this.f=new E(a):this.a=this.g();this.response=null;this.type=a}D.prototype.g=function(){return new window.XMLHttpRequest};
window.Sarissa&&Sarissa._SARISSA_IS_IE&&!(new window.XMLHttpRequest).withCredentials&&!window.XDomainRequest&&(D.prototype.g=function(){F("Sarissa");return Sarissa.originalXMLHttpRequest?new Sarissa.originalXMLHttpRequest:new window.XMLHttpRequest});D.prototype.abort=function(){this.f?this.f.abort():this.a.abort()};
D.prototype.onreadystatechange=function(){if(4==this.a.readyState){window.clearTimeout(this.h);delete this.h;var a="error";if(0==this.a.status)F(this.method+" to "+this.url+" failed: network"),this.b(!0,"connection",this.a.status);else if(200!==this.a.status){C(this.method+" to "+this.url+" failed with status: "+this.a.status);"text"===this.a.responseType&&null!==this.a.responseText&&F(this.a.responseText);if(401===this.a.status||403===this.a.status)a="authorization",this.c&&this.c.V();this.b(!1,
a,this.a.status)}else{if(""!==this.a.response){if("XML"===this.accept)this.response=this.a.responseXML&&this.a.responseXML.documentElement,null===this.response&&C("Invalid XML response: "+this.a.responseText);else if(this.m){for(var c=new Uint8Array(this.a.responseText.length),d=0;d<this.a.responseText.length;d++)c[d]=this.a.responseText.charCodeAt(d)&255;this.response=new Blob([c],{type:this.a.getResponseHeader("Content-Type")})}else if("blob"===this.a.responseType)this.response=this.a.response;
else if(this.a.responseXML)this.response=G(this.a.responseXML.childNodes[0].childNodes[0].nodeValue);else if("HTML"===this.accept||"TEXT"===this.accept)this.response=this.a.responseText;else if(this.response=G(this.a.responseText),null===this.response){F(this.method+" to "+this.url+" failed - can't parse response "+this.a.responseText);this.b(!1,a);return}if(void 0!==this.response.err&&void 0!==this.response.msg){F(this.method+" to "+this.url+" failed with error:"+this.response.err+" "+this.response.msg);
this.b(!1,a);return}}this.onsuccess(this.response)}}};function G(a){var c=null;try{c=JSON.parse(a)}catch(d){return F("JSON parse failed with error: "+d.toString()+" parsing: "+a),null}return c}D.prototype.getResponseHeader=function(a){return this.a.getResponseHeader(a)};D.prototype.get=function(a,c,d,e,g){this.method="GET";H(this,a,null,c,d,e,g)};
function H(a,c,d,e,g,m,f){a.url=c;a.onsuccess=void 0!==m?m:function(){};a.b=void 0!==f?f:function(){};a.method=a.method||"POST";if(a.f)fa(a.f,c,d,e,g,m,f);else{m=a.o||("JSON"===a.type?"application/json; charset=utf-8":"application/x-www-form-urlencoded; charset=utf-8");var v;"string"===typeof d?v=d:d instanceof Blob?(m=d.type,v=d):d&&(v="JSON"===a.type?w(d):"data="+w(d));u.safari&&a.j&&(a.h=window.setTimeout(function(){F(this.method+" to "+this.url+" failed - timedout (Safari)");this.b(!1,"timedout")}.bind(a),
a.j));a.a.onreadystatechange=function(){a.onreadystatechange()};try{a.a.open(a.method,c,e),void 0!==a.i&&a.a.setRequestHeader("Accept",a.i),void 0!==a.a.setRequestHeader&&"GET"!==a.method&&a.a.setRequestHeader("Content-type",m),a.c&&a.c.J()&&a.a.setRequestHeader("Authorization","Bearer "+a.c.J()),a.a.withCredentials=g,a.a.send(v)}catch(X){F(a.method+" to "+c+" failed with: "+X.toString()),a.b(!1,X.toString())}}}function E(a){this.type=a}
function fa(a,c,d,e,g,m,f){a.onsuccess=m;a.b=f;z({from:"IFrameProxyRequest",type:a.type,url:c,obj:d,async:e,withcred:g})}E.prototype.abort=function(){E.postMessage({from:"IFrameProxyRequest",abort:!0})};function I(a){this.name=a}function J(a,c){var d=new Date;d.setUTCHours(d.getUTCHours()+8);localStorage.setItem(a.name,w(c));localStorage.setItem(a.name+"_exp",d.toGMTString())}function K(a){if(!ga(a))return null;a=localStorage.getItem(a.name);return JSON.parse(a)}
function ha(a,c){var d=new Date;d.setUTCMinutes(d.getUTCMinutes()+c);localStorage.setItem(a.name+"_exp",d.toGMTString())}I.prototype.get=function(){return ga(this)?localStorage.getItem(this.name):null};function ga(a){var c=localStorage.getItem(a.name+"_exp");if(!c)return!1;c=new Date(c);return c<new Date?(localStorage.removeItem(a.name),localStorage.removeItem(a.name+"_exp"),!1):!0}
function L(a){this.a=a.document;this.c=a;var c=[["hidden","visibilitychange"],["mozHidden","mozvisibilitychange"],["webkitHidden","webkitvisibilitychange"],["msHidden","msvisibilitychange"],["oHidden","ovisibilitychange"]];for(a=0;a<c.length;a++)if(c[a][0]in document){this.b=c[a][0];this.f=c[a][1];break}}L.prototype.getElementsByTagName=function(a){return this.a.getElementsByTagName(a)};
function ia(a,c){var d=[["src","//www.glancecdn.net/cobrowse/js/sockjs1.0.2.min.js"]],e=a.a.createElement("script");c&&e.addEventListener("load",c);e.setAttribute("type","text/javascript");e.setAttribute("charset","UTF-8");for(var g=0;g<d.length;g++)e.setAttribute(d[g][0],d[g][1]);a.a.head.appendChild(e)}function M(a){return void 0===a.b?!1:a.a[a.b]}function ja(a,c){a.addEventListener(a.f,c)}L.prototype.head=function(){return void 0!==this.a.head?this.a.head:this.getElementsByTagName("head")[0]};
L.prototype.addEventListener=function(a,c,d){this.a.addEventListener(a,c,d)};L.prototype.removeEventListener=function(a,c,d){this.a.removeEventListener(a,c,d)};function C(a){window.console&&window.console.error&&window.console.error(a)}function F(a){window.console&&window.console.log&&window.console.log(a)};function ka(a,c){var d;a&&(d=d||Object.keys(a),d.forEach(function(d){void 0!==a[d]&&(c[d]=a[d])}))}function la(a){var c={};if(!a)return c;var d=0;for(a=a.attributes;d<a.length;d++){var e=a[d].nodeName.match(/data-(.*)/);e&&2===e.length&&(c[e[1]]=a[d].nodeValue)}return c}function ma(){var a=window.GLANCE_COBROWSE?window.GLANCE_COBROWSE:{},c=document.getElementById("glance-cobrowse"),d=la(document.getElementById("cobrowsescript")),c=la(c);ka(d,a);ka(c,a);return a};function N(){}function na(a,c){a.m="undefined"===typeof WebSocket;a.a={};a.a.ws="www.glance.net";a.a.site="production";a.g=new L(window);B(ma(),a.a);B(c,a.a);delete a.a.presenceserver;a.j=[];a.f=O;a.o=new I("glance_presence");var d=K(a.o);d&&(a.c=d.directserver)}var O=1;N.prototype.B=function(){};
function P(a,c,d,e,g){if(c&&!a.c)p("ERR_NODIRECTSERVER");else{var m=(g||"https")+"://"+(c?a.c:a.a.presenceserver)+"/"+d;e&&(m+="?",["groupid","visitorid"].forEach(function(c){m+=c+"="+a.a[c]+"&"}));return m}}N.prototype.D=function(a){oa(this,"findvisitor","GET",a)};
function Q(a){p("connecting to "+a.c);var c=!1;a.m&&!window.SockJS?ia(a.g,function(){c||(c=!0,window.SockJS?Q(a):p("ERR_NOSOCKJS"))}):(a.b&&a.b.close(),a.b=pa(a),a.b.N=a.c,a.b.onopen=function(){a.b.s({type:"connect",authorization:void 0,groupid:a.a.groupid,visitorid:a.a.visitorid,version:aa});a.j.forEach(function(c){a.b.s(c)});a.j=[];a.f=3},a.b.C=function(c){p("received:"+w(c));if(a.b){var d=c.mtype||c.type,g=c.data;switch(d){case "connected":if(a.a.nokeepalive)break;a.h||(a.h=window.setInterval(function(){a.b.s({type:"k"})},
1E3*c.keepalive));break;case "invoke":"visitor"===a.R&&ea(g);break;default:if(a["on"+d])a["on"+d](g)}}},a.b.onclose=function(c){a.b===this&&(p("Connection closed, reconnecting",this.H(c),this.I(c)),qa(a),window.setTimeout(function(){a.connect()},2E3))},a.b.onerror=function(c){a.b===this&&(a.m=!0,a.b.onclose(c))})}
function oa(a,c,d,e){function g(a){var c=a&&(a.directserver||a.direct);c&&(f.c=c,a.httpsport&&(f.c+=":"+a.httpsport),f.B());f.b&&f.c!=f.b.N&&Q(f);if(e&&e.onsuccess)e.onsuccess(a)}function m(a,d){p(c,"failed");if(e.onfail)e.onfail(d);else ra(f,{error:"connfail",detail:d})}var f=a,v=new D("JSON");v.c=void 0;v.method=d;p(c,JSON.stringify(e));(function(a){if(f.a.presenceserver)return a();var c=new I("glance_visitor_settings_"+f.a.groupid+"_"+f.a.site),d=K(c);if(d)return f.a.presenceserver=d.presenceserver,
f.a.presenceserver||p("PRES_DISABLED (from cache)"),a();var d=new D("JSON"),e="https://"+f.a.ws+"/services/authorizationservice/GetVisitorSettings2?groupid="+f.a.groupid+"&site="+f.a.site+"&service=presence";d.method="GET";H(d,e,null,!0,!1,function(d){f.a.presenceserver=d.presenceUrl;f.a.presenceserver||p("PRES_DISABLED");var e={};e.presenceserver=f.a.presenceserver;e.presencesettings=d;J(c,e);ha(c,1440);return a()},function(c,d){p("PRES_UNAVAILABLE "+d);a()})})(function(){f.a.presenceserver&&H(v,
P(f,!1,c,!0),e.data?e.data:{},!0,!0,g,m)})}function R(a){a.b&&a.b.close();qa(a)}function qa(a){a.h&&(window.clearInterval(a.h),delete a.h);a.f=O;delete a.b;delete a.c}function S(a,c){p("sending",c.type,a.f);3===a.f?a.b.s(c):(a.j.push(c),a.connect())}
N.prototype.connect=function(){if(!this.a.visitorid)p("CONN_NOVISITORID");else if(this.f===O){this.f=2;var a=this;this.onscaledown=function(){a.disconnect();a.connect()};this.c?Q(this):this.D({onsuccess:function(){p("found visitor, connect");Q(a)},onfail:function(c){ra(a,{error:"connfail",detail:c});a.f=O}})}};N.prototype.connect=N.prototype.connect;N.prototype.disconnect=function(){R(this)};N.prototype.disconnect=N.prototype.disconnect;
function ra(a,c){p("Error: ",JSON.stringify(c));if(a.onerror)a.onerror(c)}N.prototype.G=function(a,c){S(this,{type:a,data:c})};N.prototype.fire=N.prototype.G;function T(a){na(this,a);this.R="visitor";this.g=new L(window);var c=this;window.addEventListener("focus",function(){c.i=!1;c.O&&c.v()},void 0);ja(this.g,function(){p("visibility:",M(c.g)?"hidden":"visible");if(3===c.f&&!c.i){var a={type:"visibility"};a.data={visibility:M(c.g)?"hidden":"visible"};S(c,a);M(c.g)&&R(c)}});T.instance=this}var sa=T,U=["GLANCE","Presence","Visitor"],V=this;U[0]in V||!V.execScript||V.execScript("var "+U[0]);
for(var W;U.length&&(W=U.shift());)U.length||void 0===sa?V[W]?V=V[W]:V=V[W]={}:V[W]=sa;T.prototype=new N;T.prototype.B=function(){var a={};a.directserver=this.c;J(this.o,a);ha(this.o,20)};
T.prototype.v=function(a){if(this.a.visitorid){var c={};B(this.a,c,["groupid","visitorid"]);var d={},e;for(e in this.a)e.indexOf("user-")||(d[e.substring(5)]=this.a[e]);d.url=window.location.href;d.browser=u.name;d.browserver=u.version;d.platform=u.u.name;(a=a&&a.data)&&B(a,d);c.data=d;this.i||(d={type:"presence"},d.data=c.data,S(this,d),this.O=!0)}else p("PRES_NOVISITORID")};T.prototype.presence=T.prototype.v;
function pa(a){a.m?a=da(P(a,!0,"visitor")):(a=P(a,!0,"visitorws",!1,"wss"),a=new WebSocket(a),x(a));return a}T.prototype.D=function(a){a.data={};oa(this,"presence","POST",a)};T.prototype.onblur=function(){p("BLURRED");this.i=!0;R(this)};var ta=!1;function Y(){if(!ta){ta=!0;var a=ma();if(a.presence&&"api"!==a.presence){var c=new T;c.onerror=function(a){"connfail"===a.error&&window.setTimeout(function(){c.connect()},5E3)};c.v()}}}var Z=new L(window);
Z.c.addEventListener&&(document.readyState.match(/complete/)?Y():(Z.c.addEventListener("load",Y),Z.a.addEventListener("DOMContentLoaded",Y,!1)));}).call(window);
